#!/bin/bash

script_dir=`dirname $0`
. $script_dir/setup_common.sh

function setup_packages {
    # Run through the apt-get update/upgrade first. This should be done before
    # we try to install any package
    /usr/bin/apt-get -q -y update
    /usr/bin/apt-get -q -y dist-upgrade

    # Remove anacron if installed, since it stops anything
    # in /etc/cron.daily running as expected
    check_remove /usr/sbin/anacron anacron

    # Make sure cron is installed
    check_install /usr/sbin/cron cron

    # Install a MTA and web server before mailman
    # To satisfy the mailman package dependencies
    # with our desired MTA and webserver
    # Otherwise mailman would install apache+postfix
    check_install /usr/sbin/exim exim4
    check_install /usr/sbin/lighttpd lighttpd

    # Now install the mailman package
    check_install /usr/lib/mailman/bin/newlist mailman
}

function configure_exim {
    # Copy or mailman configs into the exim split directory
    # system
    cp -v $script_dir/configs/exim/04_exim4-config_mailman /etc/exim4/conf.d/main/
    cp -v $script_dir/configs/exim/40_exim4-config_mailman /etc/exim4/conf.d/transport
    cp -v $script_dir/configs/exim/101_exim4-config_mailman /etc/exim4/conf.d/router

    exim_update_conf=/etc/exim4/update-exim4.conf.conf

    # Change exim config to:
    # 1. Be a internet connected MTA
    # 2. Handle mail for our domains
    # 3. Listen on all interfaces
    # 4. Use split configuration, which will pick up files copied above 
    sed -i "s/dc_eximconfig_configtype.*$/dc_eximconfig_configtype='internet'/" $exim_update_conf
    sed -i "s/dc_other_hostnames.*$/dc_other_hostnames='sgvlug.net;sgvlug.org'/"  $exim_update_conf 
    sed -i "s/dc_local_interfaces.*$/dc_local_interfaces=''/" $exim_update_conf
    sed -i "s/dc_use_split_config.*$/dc_use_split_config='true'/" $exim_update_conf

    # Run exim update script, creates the file:
    # /var/lib/exim4/config.autogenerated
    /usr/sbin/update-exim4.conf -v

    # Restart exim
    /etc/init.d/exim4 restart
}

function configure_lighttpd {
    # Copy our configs to be included in the mail lighttpd.conf config
    cp -v $script_dir/configs/lighttpd/mailman.conf /etc/lighttpd
    cp -v $script_dir/configs/lighttpd/website.conf /etc/lighttpd

    lighttpd_config=/etc/lighttpd/lighttpd.conf

    # Disable directory listing in lighttpd config
    sed -i 's/server.dir-listing.*$/server.dir-listing          = "disable"/' $lighttpd_config

    # Add includes for our configs
    if [ -z "`grep mailman.conf $lighttpd_config`" ]; then
        cat >> $lighttpd_config <<END
# SGVLUG Lighttpd configuration
include "website.conf"
include "mailman.conf"
END
    fi

    # Restart lighttpd
    /etc/init.d/lighttpd restart
}

function configure_mailman {
    echo -n
}

#setup_packages
#configure_exim
#configure_lighttpd
configure_mailman
